services:
  - type: web
    name: bueadelights
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn bueadelights.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0  # or 3.13.4 as shown in your logs
      - key: DJANGO_SETTINGS_MODULE
        value: bueadelights.settings_prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: bueadelights.onrender.com

databases:
  - name: bueadelights-db
    plan: free