services:
  - type: web
    name: bueadelights
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn bueadelights.wsgi:application"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DJANGO_SETTINGS_MODULE
        value: bueadelights.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "bueadelights.onrender.com,.onrender.com,localhost,127.0.0.1"
      - key: WHATSAPP_NUMBER
        value: "+237699808260"
      - key: BUSINESS_NAME
        value: "BueaDelights"
      - key: BUSINESS_EMAIL
        value: "info@bueadelights.com"
      - key: DELIVERY_FEE
        value: "1500"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: PORT
        value: "10000"

databases:
  - name: bueadelights-db
    plan: free
    databaseName: bueadelights
    user: bueadelights_user