services:
  - type: web
    name: bueadelights
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn bueadelights.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: bueadelights.settings_prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: bueadelights.onrender.com
      - key: WHATSAPP_NUMBER
        value: +237699808260
      - key: BUSINESS_NAME
        value: BueaDelights
      - key: BUSINESS_EMAIL
        value: info@bueadelights.com
      - key: DELIVERY_FEE
        value: 1500
      # Add your email configuration
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: EMAIL_HOST_USER
        sync: false  # Set this in Render dashboard
      - key: EMAIL_HOST_PASSWORD
        sync: false  # Set this in Render dashboard (app password)
      # Add your Noupia payment configuration
      - key: NOUPIA_API_KEY
        sync: false  # Set this in Render dashboard
      - key: NOUPIA_MERCHANT_ID
        sync: false  # Set this in Render dashboard
      # Optional: Redis for caching (if you add Redis service)
      - key: REDIS_URL
        sync: false  # Will be set if you add Redis service
      # Optional: Sentry for error monitoring
      - key: SENTRY_DSN
        sync: false  # Set this in Render dashboard if using Sentry

databases:
  - name: bueadelights-db
    plan: free
    databaseName: bueadelights
    user: bueadelights_user

# Optional: Redis for caching and sessions
# Uncomment if you want to use Redis
# - type: redis
#   name: bueadelights-redis
#   plan: free
#   maxmemoryPolicy: allkeys-lru